# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="robbyrussell"

# Create an alias for easy Oh My ZSH configuration.

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rails ruby docker docker-compose macos brew)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim -f'
fi

# Homebrew
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# To link Rubies to Homebrew's OpenSSL 1.1 (which is upgraded):
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

# Golang
export GOPATH=$HOME/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"

# Composer
export PATH="/Users/rasmus/.composer/vendor/bin:$PATH"

# Custom aliases
alias ohmyzsh="cd ~/.oh-my-zsh" # Local instead of editing.
alias dotfiles="cd ~/Development/dotfiles"
alias ll="ls -alh"
alias rs="./bin/dev"

# Rbenv
eval "$(rbenv init -)"

# GPG key
export GPG_TTY=$(tty)
